DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS REQUESTS;

CREATE TABLE CLIENTS (
  CLIENTS_ID   BIGINT(20)  NOT NULL,
  ADDRESS      VARCHAR(200),
  COMPANY_NAME VARCHAR(50) NOT NULL,
  DESCRIPTION  VARCHAR(255),
  FIRST_NAME   VARCHAR(30),
  LAST_NAME    VARCHAR(30),
  PHONE_NUMBER VARCHAR(20) NOT NULL,
  PRIMARY KEY (CLIENTS_ID)
);

CREATE TABLE PRODUCTS (
  PRODUCT_ID    BIGINT(20) NOT NULL,
  ACTIVITY      CHAR(1),
  COLOUR        VARCHAR(30),
  GRADE         VARCHAR(20),
  INNER_HEIGHT  INT(11),
  INNER_LENGTH  INT(11),
  INNER_WIDTH   INT(11),
  PRINT         VARCHAR(30),
  PRODUCTS_NAME VARCHAR(200),
  PRODUCTS_TYPE VARCHAR(50),
  PROFILE       VARCHAR(10),
  CLIENTS_ID    BIGINT(20),
  PRIMARY KEY (PRODUCT_ID),
  FOREIGN KEY (CLIENTS_ID) REFERENCES CLIENTS (CLIENTS_ID)
);

CREATE TABLE CARDBOARD_BRAND (
  CARDBOARD_BRAND_ID BIGINT(20) NOT NULL,
  CARDBOARD_BRAND    VARCHAR(50),
  PRIMARY KEY (CARDBOARD_BRAND_ID)
);

CREATE TABLE CARDBOARD_TYPE (
  CARDBOARD_TYPE_ID BIGINT(20) NOT NULL,
  CARDBOARD_TYPE    VARCHAR(50),
  PRIMARY KEY (CARDBOARD_TYPE_ID)
);

CREATE TABLE CELLULOSIC_LAYER (
  CELLULOSIC_LAYER_ID BIGINT(20) NOT NULL,
  CELLULOSIC_LAYER    VARCHAR(50),
  PRIMARY KEY (CELLULOSIC_LAYER_ID)
);

CREATE TABLE COMPOUND (
  COMPOUND_ID BIGINT(20) NOT NULL,
  COMPOUND    VARCHAR(50),
  PRIMARY KEY (COMPOUND_ID)
);

CREATE TABLE FACE_LAYER (
  FACE_LAYER_ID BIGINT(20) NOT NULL,
  FACE_LAYER    VARCHAR(50),
  PRIMARY KEY (FACE_LAYER_ID)
);

CREATE TABLE FORMAT (
  FORMAT_ID BIGINT(20) NOT NULL,
  FORMAT    VARCHAR(50),
  PRIMARY KEY (FORMAT_ID)
);

CREATE TABLE INNER_LAYER (
  INNER_LAYER_ID BIGINT(20) NOT NULL,
  INNER_LAYER    VARCHAR(50),
  PRIMARY KEY (INNER_LAYER_ID)
);

CREATE TABLE MANUFACTURER (
  MANUFACTURER_ID BIGINT(20) NOT NULL,
  MANUFACTURER    VARCHAR(50),
  PRIMARY KEY (MANUFACTURER_ID)
);

CREATE TABLE PACKING (
  PACKING_ID BIGINT(20) NOT NULL,
  PACKING    VARCHAR(50),
  PRIMARY KEY (PACKING_ID)
);

CREATE TABLE PALLET (
  PALLET_ID BIGINT(20) NOT NULL,
  PALLET    VARCHAR(50),
  PRIMARY KEY (PALLET_ID)
);

CREATE TABLE PAPER_TYPE (
  PAPER_ID   BIGINT(20) NOT NULL,
  PAPER_TYPE VARCHAR(50),
  PRIMARY KEY (PAPER_ID)
);

CREATE TABLE PLACEMENT (
  PLACEMENT_ID BIGINT(20) NOT NULL,
  PLACEMENT    VARCHAR(50),
  PRIMARY KEY (PLACEMENT_ID)
);

CREATE TABLE PRODUCT_TYPE (
  PRODUCT_TYPE_ID BIGINT(20) NOT NULL,
  PRODUCT_TYPE    VARCHAR(50),
  PRIMARY KEY (PRODUCT_TYPE_ID)
);

CREATE TABLE PROFILE (
  PROFILE_ID BIGINT(20) NOT NULL,
  PROFILE    VARCHAR(50),
  PRIMARY KEY (PROFILE_ID)
);

CREATE TABLE ORDERS (
  ID         BIGINT      NOT NULL AUTO_INCREMENT,
  CLIENTS_ID BIGINT      NOT NULL,
  SHIP_DATE  DATETIME    NOT NULL,
  STATUS     VARCHAR(20) NOT NULL,
  CONSTRAINT FK_ORDERS_CLIENTS FOREIGN KEY (CLIENTS_ID)
  REFERENCES CLIENTS (CLIENTS_ID),
  PRIMARY KEY (ID)
);

CREATE TABLE REQUESTS (
  ID             BIGINT       NOT NULL AUTO_INCREMENT,
  ORDER_ID       BIGINT       NOT NULL,
  PRODUCTS_LIST  VARCHAR(160) NOT NULL,
  READINESS_DATE DATETIME     NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_REQUESTS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
);

CREATE TABLE REQUESTS_PRODUCTS (
  REQUESTS_ID BIGINT NOT NULL,
  PRODUCTS_ID BIGINT NOT NULL,
  PRIMARY KEY (REQUESTS_ID, PRODUCTS_ID),
  CONSTRAINT REQUESTS_PRODUCTS_1 FOREIGN KEY (REQUESTS_ID) REFERENCES REQUESTS (ID)
    ON DELETE CASCADE,
  CONSTRAINT REQUESTS_PRODUCTS_2 FOREIGN KEY (PRODUCTS_ID) REFERENCES PRODUCTS (PRODUCT_ID)
    ON DELETE CASCADE
);
