INSERT INTO CLIENTS (COMPANY_NAME, PHONE_NUMBER) VALUES ('АВК', '+38050-355-62-78');
INSERT INTO CLIENTS (COMPANY_NAME, PHONE_NUMBER) VALUES ('Ласунка', '+38066-355-62-78');
INSERT INTO CLIENTS (COMPANY_NAME, PHONE_NUMBER) VALUES ('Петрущенко', '+38067-355-62-78');

INSERT INTO PRODUCTS (CLIENT_ID,PRODUCTS_TYPE, GRADE, INNER_LENGTH, INNER_WIDTH, INNER_HEIGHT, PROFILE, COLOUR, PRINT, ACTIVITY) VALUES ('1','Ящик 4-х клапанный большой', 'Т-21', '385', '300', '180', 'B','бур/бур','АВК14','0');
INSERT INTO PRODUCTS (CLIENT_ID,PRODUCTS_TYPE, GRADE, INNER_LENGTH, INNER_WIDTH, INNER_HEIGHT, PROFILE, COLOUR, PRINT, ACTIVITY) VALUES ('2','Ящик 4-х клапанный малый', 'Т-21','410',' 300',' 180',' B','бур/бур','Ласунка','0');
INSERT INTO PRODUCTS (CLIENT_ID,PRODUCTS_TYPE, GRADE, INNER_LENGTH, INNER_WIDTH, INNER_HEIGHT, PROFILE, COLOUR, PRINT, ACTIVITY) VALUES ('3','Лоток', 'П-31', '400', '300', '145', 'BE', 'бел/бур', 'Яблоки', '0');
INSERT INTO PRODUCTS (CLIENT_ID,PRODUCTS_TYPE, GRADE, INNER_LENGTH, INNER_WIDTH, INNER_HEIGHT, PROFILE, COLOUR, PRINT, ACTIVITY) VALUES ('2','Ящик 4-х клапанный малый', 'Т-21','350',' 252',' 180', 'B', 'бур/бур', 'Ласунка', '0');
INSERT INTO PRODUCTS (CLIENT_ID,PRODUCTS_TYPE, GRADE, INNER_LENGTH, INNER_WIDTH, INNER_HEIGHT, PROFILE, COLOUR, PRINT, ACTIVITY) VALUES ('2','Ящик 4-х клапанный малый', 'Т-21', '385', '300', '180', 'B', 'бур/бур', 'Ласунка', '0');
